"""rename department

Revision ID: 889eb572e050
Revises: d489321aadd0
Create Date: 2024-04-04 23:18:29.108714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889eb572e050'
down_revision = 'd489321aadd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###